### ISSUE TITLE
5940 BREAD, 253 Boba Bots, 5026 Iron Panthers, 199 Deep Blue, 3045 Gear Gremlins, 840 Aragon Robotics in wrong locations

### ISSUE THREAD

**Issue by IPAriel** [franspaco/frc_season_map#27]
5026: in downtown Burlingame (37.582645831713315, -122.34669281506662)
253: in downtown Millbrae (37.59404324810588, -122.39020481958259)
5940: in Redwood Shores (37.532677147316576, -122.26382098395476)
199: Up the mountain (37.50599861974485, -122.2885987921678)
3045: 10-20 blocks away (37.54575700876739, -122.31674582947461)
840: Down the mountain (37.55027870290839, -122.32992853241534)

**Comment by franspaco** [comment]
Thanks!
253, 840, 5026, and 5940 were solved by #28 
199 and 3045 are addressed in #29
