### ISSUE TITLE
Events Inaccurate

### ISSUE THREAD

**Issue by amays7** [franspaco/frc_season_map#32]
I noticed that some of the team-event connections are incorrect. For example, 7125 is not connected to Amarillo, but Waco instead.

**Comment by franspaco** [comment]
Thanks for catching this. Seems like at some point TBA data was incorrect and it got cached in my update. e414013 has a fix and it should be live now. :)

**Comment by amays7** [comment]
Looks good! Thank you for the correction, and especially thank you for the site!
