### ISSUE TITLE
Update to 2024

### ISSUE THREAD

**Issue by witherslayer67** [franspaco/frc_season_map#36]
Update FRC Map to 2024 season

**Comment by flippest** [comment]
Love the map! Looking forward to seeing this update :)

**Comment by franspaco** [comment]
Took me a bit because TBA does not guarantee having a location for the events anymore, so had to go fish it out the official FIRST API and geocode, but here it is. :)

**Comment by flippest** [comment]
That makes sense.  Thank you for both the context as well as the time you've volunteered to make this happen.
